name: CI HTML

on:
  push:
    branches:
      - staging
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
      

jobs:
  htmlint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: '18'

      - name: Install HTML Hint
        run:
          npm install -g htmlhint

      - name: Run HTML Linter
        run: htmlhint "**/*.html"
          
